//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_F.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int B_id { get; set; }
        public string B_Price { get; set; }
        public string B_Name { get; set; }
        public string B_Person { get; set; }
        public string B_Rooms { get; set; }
        public string B_Days { get; set; }
        public string B_CarRent { get; set; }
    }
}
